name: Build Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - template.y*
      - samconfig.toml
      - .github/workflows/build-infra.yml

jobs:
  deploy-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Build
        run: sam build

      - name: Deploy
        run: sam deploy --no-fail-on-empty-changeset
